default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: P@ssw0rd
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_budget_development

test:
  <<: *default
  database: rails_budget_test

production:
  <<: *default
  database: rails_budget_production
  username: rails_budget
  password: <%= ENV["RAILS_BUDGET_DATABASE_PASSWORD"] %>
